DBAAS-5007: Allow label in get_training_set without a training view
splicemachine/pysplice pull request #125
Opened 2021-03-10 01:11 UTC by myles-novick

## Description
1. The get_training_set api gets an optional label param
2. The feature set that the specified label belongs to becomes the anchor set by default
3. Validation occurs to ensure all other features can be joined to the now defaulted anchor feature set

## Motivation and Context
A user should be able to specify a label even when they are not using a training view.
Fixes [DBAAS-5007](https://splicemachine.atlassian.net/browse/DBAAS-5007)

## Dependencies
[ml-worflow](https://github.com/splicemachine/ml-workflow/pull/103)

## How Has This Been Tested?
Tested against standalone and on k8s cluster using ML notebooks

2021-03-10 01:31 UTC, Ben-Epstein requested changes

2021-03-10 01:31 UTC, Ben-Epstein commented on splicemachine/features/feature_store.py
> +                                   return_pk_cols: bool = False, return_ts_col: bool = False, return_sql: bool = False) -> SparkDF or str:
docs for new params

2021-03-10 15:20 UTC, Ben-Epstein approved these changes

2021-03-12 16:13 UTC, jramineni approved these changes

2021-03-12 16:14 UTC, edriggers approved these changes

2021-03-12 16:28 UTC, merged