Dbaas 2751: Adding the stats.py module
splicemachine/pysplice pull request #19
Opened 2019-08-21 21:01 UTC by sharmanirek

Implementing: 

-  One Hot Dummy Column custom transformer
- String Index Reconstructor custom transformer (to reverse the above transformation) 
- preprocessing functions 
- Generate pdf and calculate best fitting  distribution to data  
- custom PCA calculations (exposing eigenvalues)
- PCA reconstruction functionality 
- Basic Markov Chain Object

2019-08-22 17:48 UTC, njnygaard requested changes

2019-08-22 17:48 UTC, njnygaard commented on splicemachine/ml/.vscode/settings.json
> +    "python.pythonPath": "/Users/nireksharma/anaconda3/envs/py27/bin/python"
This is a local path to a config file. I would recommend putting `.vscode/` in the `.gitignore`.

2019-08-27 13:48 UTC, Ben-Epstein requested changes

2019-08-27 13:48 UTC, Ben-Epstein commented on splicemachine/ml/stats.py
> +        elif _type == 'double' or _type == 'int' or _type == 'float':
Not sure we can assume this. I see int/long types as categorical more often than continuous variables.

2019-08-27 13:48 UTC, Ben-Epstein commented on splicemachine/ml/stats.py
> +    os.system(cmd_pip)
These need to be added to requirements.3.txt in dbaas-infrastructure, not installed here.

2019-08-27 13:48 UTC, Ben-Epstein commented on splicemachine/ml/stats.py
> +os.system('~/.local/bin/pip install -r stats_requirements.txt --user')
see above comment

2019-08-27 13:48 UTC, Ben-Epstein commented on splicemachine/ml/stats.py
> +    """Transformer to generate dummy columns for categorical variables as a part of a preprocessing pipeline
Doc strings (for all functions as well) should match our docs strings in other files (see management.py/context.py)

2019-09-03 16:15 UTC, Ben-Epstein approved these changes

2019-09-05 15:15 UTC, njnygaard approved these changes
Not really my area of expertise.

2019-09-05 20:15 UTC, merged